version: '3'

services:
  zookeeper:
    restart: on-failure
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      #- ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
  kafka:
    restart: on-failure
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      #- KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf"
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_CLIENT_USER=kafka
      - KAFKA_CLIENT_PASSWORD=kafka_password
      - KAFKA_CERTIFICATE_PASSWORD=confidential
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=confidential
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=confidential
    volumes:
    - "./kafka_jaas.conf:/bitnami/kafka/config/kafka_jaas.conf"
    - "./certs/kafka-1.jks:/bitnami/kafka/config/certs/kafka.keystore.jks"
    - "./certs/truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks"
    - "./certs/zoo-truststore.jks:/bitnami/kafka/config/certs/zookeeper.truststore.jks"
    - "./certs/zookeeper.jks:/bitnami/kafka/config/certs/zookeeper.keystore.jks"
    depends_on:
      - zookeeper
