version: "3.3"
services:
  zoo:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    hostname: zoo
    ports:
      - "2181:2181"
  kafka:
    restart: always
    depends_on:
      - zoo
    image: kafka_custom:latest
    container_name: kafka
    environment:
      - TZ="Asia/Jakarta"
    volumes:
    - "./config/kafka_jaas.conf:/home/kafka/kafka/config/kafka_jaas.conf"
    - "./config/server.properties:/home/kafka/kafka/config/server.properties"
    - "./config/zookeeper.properties:/home/kafka/kafka/config/zookeeper.properties"
    ports:
      - "9092:9092"
