version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        hostname: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181
    broker1:
        image: my_kafka:latest
        restart: always
        hostname: broker1
        ports:
          - "9091:9092"
        depends_on:
          - zoo1
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ADVERTISED_HOST_NAME: 192.168.18.60
          KAFKA_ADVERTISED_PORT: 9091
          KAFKA_HOST_NAME: broker1
          KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
          KAFKA_LISTENERS: SSL://broker1:9092
          KAFKA_ADVERTISED_LISTENERS: SSL://192.168.18.60:9091
          KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
          KAFKA_INTER_BROKER_LISTENER_NAME: SSL
        volumes:
          - /tmp/kafka/certificates/kafka.truststore:/certificates/kafka.truststore
          - /tmp/kafka/certificates/kafka.keystore:/certificates/kafka.keystore
    kafka-manager:
        image: sheepkiller/kafka-manager
        environment:
          ZK_HOSTS: zoo1:2181
        logging:
          options:
            max-file: "5"
            max-size: "10m"
        ports:
           - "9000:9000"

